;
; fixle.nasm: fix various header fields in DOS32 LE .exe generated by OpenWatcom wlink(1)
; by pts@fazekasu.hu at Tue Jan 28 17:53:29 CET 2025
;
; Compile with: nasm -0 -w+orphan-labels -f bin -DINFN="'apack3dl.exe'" -o apack3d.exe fixle.nsam
; Minimum NASM version required to compile: 0.98.39
;

pmodew_fofs equ 0x40

incbin INFN, 0, pmodew_fofs+0xe
pmodew.options db 0  ; Hide the PMODE/W logo.
incbin INFN, $-$$

; __END__
